<?php

/**
 *  _   _  ___  _  ___   _  ___  _  __  ____         __ _  
 * | \ | |/ _ \| |/ / \ | |/ _ \| |/ / / ___|  ___  / _| |___      ____ _ _ __ ___
 * |  \| | | | | ' /|  \| | | | | ' /  \___ \ / _ \| |_| __\ \ /\ / / _` | '__/ _ \ 
 * | |\  | |_| | . \| |\  | |_| | . \   ___) | (_) |  _| |_ \ V  V / (_| | | |  __/
 * |_| \_|\___/|_|\_\_| \_|\___/|_|\_\ |____/ \___/|_|  \__| \_/\_/ \__,_|_|  \___|
 *  -================================================================
 *  Plugin Scaffold generated by NOKNOK WP Plugin Scaffold
 * 
 * Plugin Name:         {{ cookiecutter.plugin_slug }}
 * Description:         {{ cookiecutter.plugin_description }}
 * Version:             0.0.1-alpha.0
 * Author:              {{ cookiecutter.author_name }}
 * Author URI:          {{ cookiecutter.author_uri }}
 * Text Domain:         {{ cookiecutter.text_domain }}
 * Domain Path:         /languages 
{%- if cookiecutter.github_plugin_uri %}
 * GitHub Plugin URI:   {{ cookiecutter.github_plugin_uri }}
 * Release Asset:       true
{%- endif %}
 */

use {{ cookiecutter.plugin_namespace }}\PluginLoader;

if( !defined( 'ABSPATH' ) ) exit;

define( "{{ cookiecutter.constant_prefix }}_TEXT_DOMAIN", "{{ cookiecutter.text_domain }}" );
define( "{{ cookiecutter.constant_prefix }}_DIR", plugin_dir_path( __FILE__ ) );
define( "{{ cookiecutter.constant_prefix }}_URL", plugin_dir_url( __FILE__ ) );
define( "{{ cookiecutter.constant_prefix }}_FILE", __FILE__ );

{% if cookiecutter.use_prefixer|int -%}
$autoload_files_cache = &$GLOBALS['__composer_autoload_files']; // Get Autoload Files Cache ByRef
$autoload_files_cache = array(); // Flush composers file identifier cache so we can reload identical ID's
{%- endif -%}

require_once {{ cookiecutter.constant_prefix }}_TEXT_DOMAIN . 'vendor/autoload.php';

{%- if cookiecutter.use_prefixer|int -%}
$autoload_files_cache = array(); // Flush again to prevent a future conflict
{%- endif %}

function {{ cookiecutter.function_prefix }}_loaded() {
    PluginLoader::init();
}

add_action( '{{ cookiecutter.function_prefix }}_loaded', '{{ cookiecutter.function_prefix }}_loaded' );
do_action( '{{ cookiecutter.function_prefix }}_loaded' );

